### ISSUE TITLE
Kibana status dashboard import fails

### ISSUE THREAD

**Issue by jdpedrie** [DigitalPebble/storm-crawler#759] opened 2019-10-01 16:22 UTC
Following the [instructions](https://github.com/DigitalPebble/storm-crawler/blob/master/external/elasticsearch/README.md#kibana) for importing dashboards, I receive an error when importing the `Top-Hosts` visualization from `status.json`:

> Could not locate that index-pattern-field (id: metadata.hostname)

When inspecting data in the index, `metadata.hostname` does appear as expected.

**Comment by jnioche** [comment] 2019-10-02 06:09
thanks @jdpedrie, I have updated the instructions in the README. Will try to reproduce the steps later and see if I am getting the same problem

**Comment by jnioche** [comment] 2019-10-02 15:11
Did you load the dashboards before running the crawl? or was the crawl topology already started?

**Comment by jdpedrie** [comment] 2019-10-02 15:19
The crawl was already begun.

**Comment by jnioche** [comment] 2019-10-03 20:20
Weird, could you please reload the index pattern, check that _metadata.hostname_ is listed and re-import the dashboard?

I am tempted to add a field explicitly in the mapping ('_key_'?) and refer to it in the visualization instead of relying on something that can vary from one configuration to the next.

**Comment by jnioche** [comment] 2019-10-03 20:49
#761 should prevent this in the future. For your existing crawl, reloading the index pattern should do the trick. Let me know how it goes.

**Comment by jnioche** [comment] 2019-10-10 10:47
Closing for now, #761 seems to be working. Please reopen if necessary

**Closed by jnioche** 2019-10-10 10:47 UTC
Labels: bug
