### ISSUE TITLE
Issue while connecting to elasticsearch

### ISSUE THREAD

**Issue by raaz1234** [DigitalPebble/storm-crawler#453] opened 2017-04-08 18:32 UTC
What kind of issue is this?

 - [x] Question. 
Hello,

I have been following video blog on  Storm Crawler.

I am trying to create a web crawler referring the WIKI<https://github.com/DigitalPebble/storm-crawler/tree/master/external/elasticsearch > and video <https://www.youtube.com/watch?v=xMCuWpPh-4A&feature=youtu.be> , but I am getting:

**java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0]**

I am using following:
Elasticsearch : 5.3.0 version
Storm: 1.0.3 version.

Please help me with what versions are recommended and used by you.

Appreciate your help.

Thanks!
Raj

**Comment by jnioche** [comment] 2017-04-08 21:31
Please use StackOverflow in the future for asking questions such as these.
The video is based on the archetype 1.4 which uses ES 2.x but we've upgraded to ES5 since. Clone the repo, build with `mvn clean install` and recreate a new project with the archetype again but this time specifying 1.5-SNAPSHOT. This should get you the right dependencies for ES5.

**Comment by jnioche** [comment] 2017-04-09 14:24
Thanks @raaz1234 for opening http://stackoverflow.com/questions/43307698/issue-while-connecting-to-elasticsearch

Closing this issue for now, assuming that the problem is sorted.

**Closed by jnioche** 2017-04-09 14:24 UTC
