### ISSUE TITLE
Enhancement: Access to JSoup Document from ParseFilters

### ISSUE THREAD

**Issue by owenrh** [DigitalPebble/storm-crawler#472] opened 2017-06-02 10:44 UTC
For pages with malformed HTML there are scenarios where the XPathFilter, etc, are unable to parse some links present in a page. However, I've found that JSoup is able to parse links from the content.

Consequently, it would be really helpful to be able to access the JSoup Document created by the JSoupParser bolt in the parse filters themselves, or have the ability to create JSoup specific filters. I guess the former would require an API change, but the latter would split the emitting of links across the codebase unnecessarily.

As a work around, I've updated our custom JSoupParserBolt to attach the JSoup document onto ThreadLocal - but this is obviously a big old hack : o

**Comment by jnioche** [comment] 2017-06-02 10:57
if you can access the data from the JSoup Document there it should be possible to get that across to the DOM representation in [JSoupDOMBuilder](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/parse/JSoupDOMBuilder.java), shouldn't it?

**Comment by owenrh** [comment] 2017-06-02 11:37
@jnioche I'm not familiar with JSoupDomBuilder, but I guess you're saying that a modification to that would mean the links could make their way into the DocumentFragment passed into the parse filters. 

So then the XPathFilter would find the now well-formed links?

**Comment by jnioche** [comment] 2017-06-02 11:38
Exactly.

**Comment by owenrh** [comment] 2017-06-02 12:18
Cool, when I've got a mo I'll have a look at it and see if I can patch it somehow.

**Comment by jnioche** [comment] 2017-10-06 12:10
Can't reproduce, closing for now

**Closed by jnioche** 2017-10-06 12:10 UTC
Labels: ideas
