### ISSUE TITLE
NPE in function MetadataTransfert.filter()

### ISSUE THREAD

**Issue by ludovic-boutros** [DigitalPebble/storm-crawler#168] opened 2015-08-13 09:05 UTC
Hi,

the parameter 'metadata' can be null in the function MetadataTransfert.filter().
It throws a NPE later.

Just adding the test and returning 'md' fix this issue.

**Comment by jnioche** [comment] 2015-08-27 09:21
@ludovic-boutros did you get the NPE after I reverted your PR? Would be good to find where we get a null metadata.

**Comment by ludovic-boutros** [comment] 2015-08-27 11:28
Not yet. I will try soon.

**Comment by ludovic-boutros** [comment] 2015-08-27 12:10
Ok I reproduce the issue while running the Solr seed injector example. 
Will try to figure out what's wrong here.

**Comment by ludovic-boutros** [comment] 2015-08-27 12:12
It seems that the FileSpout emits null metadata...

**Comment by jnioche** [comment] 2015-08-27 13:24
So this would mean that [https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/bolt/URLPartitionerBolt.java#L69] should also check for the value of metadata. In the case you found we were emitting a field metadata but with a null value. I'll fix this.

**Comment by jnioche** [comment] 2015-08-27 13:32
@ludovic-boutros please close this issue if you are confident that the problem is now solved. Thanks

**Closed** 2015-08-27 13:50 UTC
