### ISSUE TITLE
ESStatusUpdater delayed FETCHED status writes

### ISSUE THREAD

**Issue by hironroy** [DigitalPebble/storm-crawler#314] opened 2016-07-11 13:03 UTC
Hi, thanks for all the great work you guys have been doing on Storm Crawler!

When I run my crawl topology on a Storm Cluster (instead of on a local cluster), I'm not seeing any "FETCHED" statuses appear in the ES `status` index for a day or so. After the "FETCHED" statuses start appearing (after a day), they update at a rate that reflects the fetch rate.

Is this expected behavior? Am I configuring the ESStatusUpdater incorrectly?

Thanks in advance for any guidance and help!

**Comment by jnioche** [comment] 2016-07-11 14:42
Hi, thanks for your kind words.

This is definitely not the expected behaviour. The FETCHED should indeed match the fetch rate but should not take a day to appear on the index.

Can you share your ES and crawl configs? What sort of pages do you crawl for? Do they contain many outlinks? Any messages on the logs?

**Comment by hironroy** [comment] 2016-07-12 14:28
Thanks! I'll be troubleshooting tonight, at which time, I'll compile and share my configs and logs.

To familiarize myself with storm-crawler, I've been pointing at Reddit's home page and limiting the crawl to subreddit and topic comment pages. There are a lot outlinks being emitted for the average page.

With basic poking around and grep-ing the Storm-Supervisor logs, I haven't found any error messages. I'm in the middle of setting up Logstash, so I'll be able to provide more details shortly.

Additionally, I'm going to install the BigHead plugin to my ES instance and see if the issue lies in the indexing performance.

Thanks Again.

**Comment by hironroy** [comment] 2016-07-13 00:08
Got caught up with other work tasks, but will get on this tomorrow morning.

**Comment by jnioche** [comment] 2016-07-19 15:33
Hi @hironroy - still an issue or can we close this?

**Comment by hironroy** [comment] 2016-07-21 18:45
Looking at the performance metrics of the ES instance, I think the bottleneck is occurring there, so closing the issue makes sense. If I find anything that contradicts that, I'll update you. Thanks!

**Comment by jnioche** [comment] 2016-07-21 20:47
OK. It makes sense to give ES plenty of memory and fast disks in write-heavy situations e.g. when there's many outlinks discovered.
Having said that, it should definitely not take a day for the status to get updated. 
Wondering whether it could be that you get tuple timeouts on the URLs fetched because they have too many outlinks to write to ES first and so they get removed from the cache in the spout and get replayed next time round. If you look at the logs, do you see the same URLS being refetched again and again?

**Closed** 2016-07-28 07:01 UTC
Labels: question
